### ISSUE TITLE
Increase VM size for default node pool

### ISSUE THREAD

**Issue by brendangadd** [StatCan/terraform-kubernetes-aks-daaas#2]
Expect analysis that exceeds D8 compute. Increase VM size for default node pool to support resource-intensive workloads.

**Comment by zachomedia** [comment]
I would recommend for any heavy analysis that we should have a dedicated compute pool for this (with the appropriate selectors + taints/tolerations). 

The default node pool runs the cluster platform control plane as well as low-resource tasks such as running web applications.

**Comment by sylus** [comment]
Think this was agreed on :D
