### ISSUE TITLE
Auto-scaling halted by network IP space

### ISSUE THREAD

**Issue by brendangadd** [StatCan/terraform-kubernetes-aks-daaas#3]
In our current workload state, the cluster currently can't scale past ~15 nodes. A much larger network IP space is required.

Root cause discovered by @justbert:
```
Scale-up failed for group <nodepool>: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="SubnetIsFull" Message="Subnet containers with address prefix <CIDR bloc> does not have enough capacity for 549 IP addresses." Details=[]
```

**Comment by justbert** [comment]
Seems that adding a nodepool in a seperate subnet is in beta. 
Is the control plane in the subnet? The seperate nodepool will need to be able to contact it to work.
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#add-a-node-pool-with-a-unique-subnet-preview

**Comment by justbert** [comment]
We may be able to:
- Add a new user nodepool in the VNet on a larger subnet
- Switch the original nodepool to one of type system
- Scale up the user nodepool
- Scale down the original node pool

This might work since
> Azure routes traffic between all subnets within a virtual network, by default.

but this feature is in preview, as stated in the previous comment block.

**Comment by brendangadd** [comment]
@justbert 
* Goal is to return to a single larger subnet, so we would want to do this with both of our current node pools, correct?
* Once the existing node pools are trashed, will we able to make the terraform reconciler happy with the result (i.e. reporting that our terraform config is aligned to current state)?

**Comment by justbert** [comment]
No, I don't think it will be possible to move the control plane off the original node pool. @zachomedia can respond with more confidence to that.

We'd have a nodepool for the control plane (mode=system) and a GPU nodepool on the original subnet, and a nodepool (mode=user) on a new subnet with many more IP addresses available. 

The original subnet technically doesn't have enough IP addresses for the current amount of maxnodes for the gpupool, but that can be massaged.

**Comment by sylus** [comment]
New cluster has been launched and all applications ported.

Only issue now is data migration.
